#index:
#    path: /
#    controller: App\Controller\DefaultController::index

messenger:
  path: /messenger
  controller: App\Controller\MessengerAction
  methods: [GET]

#health_check:
#  path: /
#  controller: App\Controller\HealthCheckController
#  methods: [GET]